export const STUDIO_HTML=String.raw`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SOOP Unified Core Studio</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:#e8eef8;background:#09111f;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#14243f 0,#09111f 44%);min-height:100vh}.wrap{max-width:1480px;margin:auto;padding:26px}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:20px}.brand h1{margin:0;font-size:24px;letter-spacing:-.02em}.brand p{margin:6px 0 0;color:#91a1ba}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn,input{border:1px solid #2b3b59;background:#101c30;color:#e8eef8;border-radius:10px;padding:10px 12px}.btn{cursor:pointer}.btn:hover{border-color:#4c6f9f}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.card{background:rgba(16,28,48,.9);border:1px solid #243754;border-radius:16px;padding:16px;box-shadow:0 14px 34px rgba(0,0,0,.18)}.kpi b{font-size:27px;display:block;margin-top:8px}.muted{color:#91a1ba}.ok{color:#7ce3a1}.warn{color:#ffc86b}.bad{color:#ff7a90}.section{margin-top:16px}.section h2{font-size:16px;margin:0 0 12px}.tablewrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:left;padding:10px;border-bottom:1px solid #21324d;vertical-align:top;white-space:nowrap}.table th{color:#90a3c0;font-weight:600;position:sticky;top:0;background:#101c30}.row{cursor:pointer}.row:hover{background:#14233b}.pill{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:12px;background:#1b2b45}.pill.ok{background:#123826}.pill.warn{background:#443514}.pill.bad{background:#48202a}.cols{display:grid;grid-template-columns:2fr 1fr;gap:16px}.empty{padding:22px;color:#91a1ba;text-align:center}.detail{white-space:pre-wrap;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;max-height:420px;overflow:auto;line-height:1.55}.toolbar{display:flex;gap:8px;align-items:center;margin-bottom:10px}.toolbar input{flex:1}.meta{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px}.footer{margin-top:18px;color:#71829d;font-size:12px}.dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:6px;background:currentColor}@media(max-width:1050px){.grid{grid-template-columns:repeat(3,1fr)}.cols{grid-template-columns:1fr}.wrap{padding:16px}}@media(max-width:620px){.grid{grid-template-columns:repeat(2,1fr)}.top{flex-direction:column}.actions{width:100%}.actions input{flex:1;min-width:0}.table th,.table td{padding:9px 8px}}
</style></head><body><main class="wrap"><div class="top"><div class="brand"><h1>SOOP Unified Core Studio <span class="muted">v2.4</span></h1><p>연결 · 데이터 무결성 · Provider · 런타임 · 장애 원인을 한 화면에서 확인합니다.</p></div><div class="actions"><input id="key" type="password" autocomplete="off" placeholder="API Key (필요한 경우)"><button class="btn" id="save">적용</button><button class="btn" id="snapshot">진단 복사</button><button class="btn" id="refresh">새로고침</button></div></div>
<div class="grid" id="kpis"></div><div class="cols section"><section class="card"><div class="toolbar"><h2 style="margin:0">실시간 연결</h2><input id="search" placeholder="방송 ID 검색"></div><div id="streams"></div></section><section class="card"><h2>Provider 상태</h2><div id="providers"></div></section></div><div class="cols section"><section class="card"><h2>선택한 방송 디버깅</h2><div id="streamDetail" class="detail muted">방송 행을 누르면 connect/JOIN/disconnect/reconnect 타임라인을 볼 수 있습니다.</div></section><section class="card"><h2>최근 문제 / 진단</h2><div id="diagnostics" class="detail muted">불러오는 중…</div></section></div><div class="footer">자동 갱신 5초 · 빨강은 즉시 확인, 노랑은 복구/대기/불확실 상태입니다. Global seq 숫자 점프만으로 누락을 판단하지 말고 gap 알림을 기준으로 보세요.</div></main>
<script>
const $=s=>document.querySelector(s);let latest={streams:[],diag:null,health:null},selected='';const key=sessionStorage.getItem('soopKey')||'';$('#key').value=key;$('#save').onclick=()=>{sessionStorage.setItem('soopKey',$('#key').value);load()};$('#refresh').onclick=load;$('#search').oninput=renderStreams;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const h=()=>{const k=sessionStorage.getItem('soopKey')||'';return k?{'x-api-key':k}:{}};
const pill=s=>{const c=['healthy','entered','fresh','online','closed'].includes(s)?'ok':['broken','blocked','protocol-error','open'].includes(s)?'bad':'warn';return '<span class="pill '+c+'"><span class="dot"></span>'+esc(s)+'</span>'};
const bytes=n=>{n=Number(n||0);if(n>1073741824)return(n/1073741824).toFixed(1)+' GB';if(n>1048576)return(n/1048576).toFixed(0)+' MB';if(n>1024)return(n/1024).toFixed(0)+' KB';return n+' B'};
const ago=ms=>ms==null?'—':ms<1000?Math.round(ms)+'ms 전':ms<60000?Math.round(ms/1000)+'초 전':Math.round(ms/60000)+'분 전';
async function j(path){const r=await fetch(path,{headers:h()});if(!r.ok)throw new Error(path+' HTTP '+r.status);return r.json()}
function renderStreams(){const q=$('#search').value.trim().toLowerCase(),ss=(latest.streams||[]).filter(x=>!q||String(x.streamerId).toLowerCase().includes(q));$('#streams').innerHTML=ss.length?'<div class="tablewrap"><table class="table"><thead><tr><th>방송</th><th>상태</th><th>무결성</th><th>마지막 이벤트</th><th>수집</th><th>중복</th><th>Gap 후보</th><th>최근 원인</th></tr></thead><tbody>'+ss.map(x=>{const d=x.diagnostics||{},last=d.lastError||d.lastCloseReason||'';return '<tr class="row" data-id="'+esc(x.streamerId)+'"><td><b>'+esc(x.streamerId)+'</b><div class="muted">refs '+esc(x.refs)+'</div></td><td>'+pill(x.state)+'</td><td>'+pill(x.integrity)+'</td><td>'+esc(ago(x.lastEventAgeMs))+'</td><td>'+esc(x.acceptedEvents||0)+'</td><td>'+esc(x.duplicates||0)+'</td><td class="'+((x.possibleGaps||0)?'warn':'')+'">'+esc(x.possibleGaps||0)+'</td><td class="muted" title="'+esc(last)+'">'+esc(last||'—')+'</td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">현재 조건에 맞는 연결이 없습니다.</div>';document.querySelectorAll('.row').forEach(el=>el.onclick=()=>{selected=el.dataset.id||'';renderDetail()})}
function renderDetail(){const x=(latest.streams||[]).find(x=>x.streamerId===selected);if(!x)return;const d=x.diagnostics||{},tl=(d.timeline||[]).slice().reverse().map(t=>t.at+'  '+t.type+(t.code!=null?' ['+t.code+']':'')+(t.detail?'  '+t.detail:'')).join('\n'),g=(x.recentGaps||[]).slice().reverse().map(a=>'possible gap: '+a.from+' → '+(a.to||'진행 중')+(a.reason?' · '+a.reason:'')).join('\n');$('#streamDetail').textContent=['streamer: '+x.streamerId,'state: '+x.state+' / integrity: '+x.integrity,'packetsIn: '+(d.packetsIn||0)+' / accepted: '+(x.acceptedEvents||0)+' / duplicates: '+(x.duplicates||0),'lastInbound: '+(d.lastInboundAt||'—'),'lastJoin: '+(d.lastJoinAt||'—'),'nextRetry: '+(d.nextRetryAt||'—'),'','[possible gaps]',g||'없음','','[connection timeline]',tl||'기록 없음'].join('\n')}
async function load(){try{const [health,streams,diag,metrics]=await Promise.all([j('/v1/health'),j('/v1/streams'),j('/v1/diagnostics'),j('/v1/metrics')]);latest={health,streams:streams.streams||[],diag,metrics};const ss=latest.streams,prov=health.providers||[],entered=ss.filter(x=>x.state==='entered').length,reconnect=ss.filter(x=>['reconnecting','offline-wait','connecting','connected'].includes(x.state)).length,broken=ss.filter(x=>x.integrity==='broken').length,gaps=ss.reduce((n,x)=>n+Number(x.possibleGaps||0),0),gauges=metrics.gauges||{},gv=n=>gauges[n+'|']?.value??0,lag=gv('soop_runtime_event_loop_lag_ms'),rss=gv('soop_runtime_rss_bytes');$('#kpis').innerHTML=[['전체 상태',broken?'주의':'정상',broken?'bad':'ok'],['수집 방송',ss.length,''],['정상 연결',entered,'ok'],['재연결/대기',reconnect,reconnect?'warn':''],['Gap 후보',gaps,gaps?'warn':'ok'],['Event-loop',Math.round(lag)+' ms',lag>100?'bad':lag>30?'warn':'ok'],['메모리',bytes(rss),''],['Unknown 패킷',diag.drift?.unknownEvents||0,(diag.drift?.unknownEvents||0)?'warn':'ok']].map(x=>'<div class="card kpi"><span class="muted">'+x[0]+'</span><b class="'+x[2]+'">'+x[1]+'</b></div>').join('');$('#providers').innerHTML=prov.length?'<div class="tablewrap"><table class="table"><tbody>'+prov.map(p=>'<tr><td><b>'+esc(p.name)+'</b><div class="muted">'+esc(Math.round(p.latencyMs||0))+' ms · weight '+esc(p.dynamicWeight??'—')+'</div></td><td>'+pill(p.state)+'</td><td class="muted">'+esc(p.lastError||'')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Provider 없음</div>';renderStreams();if(selected)renderDetail();const recent=(diag.anomalies||[]).slice(0,10).map(a=>a.receivedAt+'  '+a.streamerId+'  '+a.kind+'  '+(a.detail||'')).join('\n');$('#diagnostics').textContent=recent||'최근 anomaly 없음';}catch(e){$('#diagnostics').textContent='불러오기 실패: '+e.message+'\nAPI Key가 설정돼 있다면 위 입력란에 넣어주세요.'}}
$('#snapshot').onclick=async()=>{try{const data=await j('/v1/diagnostics');await navigator.clipboard.writeText(JSON.stringify({at:new Date().toISOString(),health:latest.health,streams:latest.streams,diagnostics:data},null,2));$('#snapshot').textContent='복사됨';setTimeout(()=>$('#snapshot').textContent='진단 복사',1200)}catch(e){$('#diagnostics').textContent='진단 복사 실패: '+e.message}};
load();setInterval(load,5000);
</script></body></html>`;
