import type{IncomingMessage}from'node:http';
import WebSocket,{WebSocketServer}from'ws';
import type{CanonicalEvent}from'../types.js';
import type{UnifiedService}from'../core/unified-service.js';
import type{AppConfig}from'../config.js';
import{eventDescriptor}from'../protocol/catalog.js';

interface SequencedEvent{seq:number;event:CanonicalEvent}
class ReplayRing{private data:Array<SequencedEvent|undefined>;private start=0;private count=0;constructor(private capacity:number){this.data=new Array(capacity)}push(v:SequencedEvent){const i=(this.start+this.count)%this.capacity;if(this.count<this.capacity){this.data[i]=v;this.count++}else{this.data[this.start]=v;this.start=(this.start+1)%this.capacity}}items(){const out:SequencedEvent[]=[];for(let i=0;i<this.count;i++){const v=this.data[(this.start+i)%this.capacity];if(v)out.push(v)}return out}oldestSeq(fallback:number){return this.count?(this.data[this.start]?.seq??fallback):fallback}}
interface ClientState{subs:Map<string,Set<string>|null>;lastPongAt:number;queue:Promise<void>;gapFrom?:number;gapTo?:number;lastSeq?:number}

export function eventMatchesFilter(filter:Set<string>|null,e:CanonicalEvent){const baseType=eventDescriptor(e.code).name;return !filter||filter.has(e.type)||filter.has(baseType)||filter.has(String(e.code))||filter.has(e.category)}

export class WsHub{
 readonly wss:WebSocketServer;private states=new WeakMap<WebSocket,ClientState>();private heartbeat?:NodeJS.Timeout;private seq=0;private replay:ReplayRing;
 constructor(private service:UnifiedService,private cfg:AppConfig){this.replay=new ReplayRing(cfg.wsReplayEvents);this.wss=new WebSocketServer({noServer:true,maxPayload:cfg.wsMaxPayloadBytes,perMessageDeflate:false});this.wss.on('connection',ws=>this.onConnection(ws));service.pool.on('event',(e:CanonicalEvent)=>this.broadcast(e));const interval=Math.max(5000,Math.min(30000,Math.floor(cfg.wsClientIdleMs/2)));this.heartbeat=setInterval(()=>this.heartbeatClients(),interval);this.heartbeat.unref?.()}
 handleUpgrade(req:IncomingMessage,socket:any,head:Buffer){if(this.wss.clients.size>=this.cfg.maxWsClients){this.service.metrics.inc('soop_ws_client_rejected_total');socket.destroy();return}this.wss.handleUpgrade(req,socket,head,ws=>this.wss.emit('connection',ws,req))}
 private onConnection(ws:WebSocket){const st:ClientState={subs:new Map(),lastPongAt:Date.now(),queue:Promise.resolve()};this.states.set(ws,st);this.service.metrics.inc('soop_ws_clients_connected_total');this.service.metrics.set('soop_ws_clients_active',this.wss.clients.size);this.send(ws,{type:'hello',protocol:4,actions:['subscribe','unsubscribe','list','ping','resume'],maxSubscriptions:this.cfg.maxWsSubscriptions,replayEvents:this.cfg.wsReplayEvents,currentSeq:this.seq});ws.on('pong',()=>{st.lastPongAt=Date.now()});ws.on('message',buf=>{st.queue=st.queue.then(()=>this.onMessage(ws,buf.toString())).catch(err=>{this.service.metrics.inc('soop_ws_client_command_errors_total');this.send(ws,{type:'error',error:'command_failed',detail:err instanceof Error?err.message:String(err)})})});ws.on('close',()=>{for(const id of st.subs.keys())this.service.pool.release(id);this.service.metrics.inc('soop_ws_clients_disconnected_total');queueMicrotask(()=>this.service.metrics.set('soop_ws_clients_active',this.wss.clients.size))});ws.on('error',()=>this.service.metrics.inc('soop_ws_client_errors_total'))}
 private heartbeatClients(){const now=Date.now();for(const ws of this.wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const st=this.states.get(ws);if(!st)continue;if(now-st.lastPongAt>this.cfg.wsClientIdleMs){this.service.metrics.inc('soop_ws_client_idle_terminated_total');try{ws.terminate()}catch{}continue}if(st.gapFrom!==undefined&&ws.bufferedAmount<=this.cfg.wsBackpressureBytes)this.flushGap(ws,st);try{ws.ping()}catch{}}}
 private matches(st:ClientState,e:CanonicalEvent){const filter=st.subs.get(e.streamerId);if(filter===undefined)return false;return eventMatchesFilter(filter,e)}
 private async onMessage(ws:WebSocket,text:string){let m:any;try{m=JSON.parse(text)}catch{return this.send(ws,{type:'error',error:'invalid_json'})}const st=this.states.get(ws);if(!st)return;if(m.action==='ping')return this.send(ws,{type:'pong',at:new Date().toISOString(),seq:this.seq});if(m.action==='list')return this.send(ws,{type:'subscriptions',streamers:[...st.subs.keys()],lastSeq:st.lastSeq});if(m.action==='resume'){const from=Number(m.fromSeq);if(!Number.isSafeInteger(from)||from<0)return this.send(ws,{type:'error',error:'invalid_from_seq'});return this.resume(ws,st,from)}if(!['subscribe','unsubscribe'].includes(m.action))return this.send(ws,{type:'error',error:'unknown_action'});const ids=[...new Set((Array.isArray(m.streamers)?m.streamers:[]).filter(validId))] as string[];if(m.action==='subscribe'){if(st.subs.size+ids.filter(id=>!st.subs.has(id)).length>this.cfg.maxWsSubscriptions)return this.send(ws,{type:'error',error:'subscription_limit'});const filter=Array.isArray(m.events)?new Set<string>(m.events.map(String)):null;for(const id of ids){if(!st.subs.has(id)){await this.service.pool.acquire(id);if(ws.readyState!==WebSocket.OPEN){this.service.pool.release(id);return}st.subs.set(id,filter)}else st.subs.set(id,filter)}this.send(ws,{type:'subscribed',streamers:ids,events:filter?[...filter]:null,currentSeq:this.seq,sequenceScope:'global'})}else{for(const id of ids)if(st.subs.delete(id))this.service.pool.release(id);this.send(ws,{type:'unsubscribed',streamers:ids,currentSeq:this.seq})}}
 private resume(ws:WebSocket,st:ClientState,fromSeq:number){const oldest=this.replay.oldestSeq(this.seq);if(fromSeq<oldest-1){this.service.metrics.inc('soop_ws_resume_unavailable_total');return this.send(ws,{type:'resume_unavailable',fromSeq,oldestAvailableSeq:oldest,currentSeq:this.seq})}let replayed=0;for(const item of this.replay.items()){if(item.seq<=fromSeq||!this.matches(st,item.event))continue;if(ws.bufferedAmount>this.cfg.wsBackpressureBytes){this.markGap(st,item.seq);break}this.flushGap(ws,st);this.send(ws,{type:'event',seq:item.seq,sequenceScope:'global',replayed:true,event:item.event});st.lastSeq=item.seq;replayed++}this.send(ws,{type:'resumed',fromSeq,replayed,currentSeq:this.seq})}
 private markGap(st:ClientState,seq:number){st.gapFrom??=seq;st.gapTo=seq;this.service.metrics.inc('soop_ws_backpressure_drops_total')}
 private flushGap(ws:WebSocket,st:ClientState){if(st.gapFrom===undefined)return;this.send(ws,{type:'gap',fromSeq:st.gapFrom,toSeq:st.gapTo,dropped:(st.gapTo??st.gapFrom)-st.gapFrom+1,currentSeq:this.seq});this.service.metrics.inc('soop_ws_gap_notifications_total');st.gapFrom=st.gapTo=undefined}
 private broadcast(e:CanonicalEvent){const seq=++this.seq;this.replay.push({seq,event:e});for(const ws of this.wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const st=this.states.get(ws);if(!st||!this.matches(st,e))continue;if(ws.bufferedAmount>this.cfg.wsBackpressureBytes){this.markGap(st,seq);continue}this.flushGap(ws,st);this.send(ws,{type:'event',seq,sequenceScope:'global',event:e});st.lastSeq=seq}}
 private send(ws:WebSocket,data:any){try{ws.send(JSON.stringify(data))}catch{this.service.metrics.inc('soop_ws_send_errors_total')}}
 async close(){if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=undefined;for(const ws of this.wss.clients)try{ws.terminate()}catch{};await new Promise<void>(resolve=>{try{this.wss.close(()=>resolve())}catch{resolve()}})}
}
export function validId(id:any):id is string{return typeof id==='string'&&/^[A-Za-z0-9_-]{1,64}$/.test(id)}
