import type{IncomingMessage}from'node:http';import WebSocket,{WebSocketServer}from'ws';import type{CanonicalEvent}from'../types.js';import type{UnifiedService}from'../core/unified-service.js';import type{AppConfig}from'../config.js';
interface ClientState{subs:Map<string,Set<string>|null>;lastPongAt:number}
export class WsHub{
 readonly wss:WebSocketServer;private states=new WeakMap<WebSocket,ClientState>();private heartbeat?:NodeJS.Timeout;
 constructor(private service:UnifiedService,private cfg:AppConfig){
  this.wss=new WebSocketServer({noServer:true,maxPayload:cfg.wsMaxPayloadBytes,perMessageDeflate:false});
  this.wss.on('connection',ws=>this.onConnection(ws));service.pool.on('event',(e:CanonicalEvent)=>this.broadcast(e));
  const interval=Math.max(5000,Math.min(30000,Math.floor(cfg.wsClientIdleMs/2)));this.heartbeat=setInterval(()=>this.heartbeatClients(),interval);this.heartbeat.unref?.();
 }
 handleUpgrade(req:IncomingMessage,socket:any,head:Buffer){if(this.wss.clients.size>=this.cfg.maxWsClients){this.service.metrics.inc('soop_ws_client_rejected_total');socket.destroy();return}this.wss.handleUpgrade(req,socket,head,ws=>this.wss.emit('connection',ws,req))}
 private onConnection(ws:WebSocket){const st:ClientState={subs:new Map(),lastPongAt:Date.now()};this.states.set(ws,st);this.service.metrics.inc('soop_ws_clients_connected_total');this.service.metrics.set('soop_ws_clients_active',this.wss.clients.size);this.send(ws,{type:'hello',protocol:3,actions:['subscribe','unsubscribe','list','ping'],maxSubscriptions:this.cfg.maxWsSubscriptions});ws.on('pong',()=>{st.lastPongAt=Date.now()});ws.on('message',buf=>void this.onMessage(ws,buf.toString()));ws.on('close',()=>{for(const id of st.subs.keys())this.service.pool.release(id);this.service.metrics.inc('soop_ws_clients_disconnected_total');queueMicrotask(()=>this.service.metrics.set('soop_ws_clients_active',this.wss.clients.size))});ws.on('error',()=>this.service.metrics.inc('soop_ws_client_errors_total'))}
 private heartbeatClients(){const now=Date.now();for(const ws of this.wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const st=this.states.get(ws);if(!st)continue;if(now-st.lastPongAt>this.cfg.wsClientIdleMs){this.service.metrics.inc('soop_ws_client_idle_terminated_total');try{ws.terminate()}catch{}continue}try{ws.ping()}catch{}}}
 private async onMessage(ws:WebSocket,text:string){let m:any;try{m=JSON.parse(text)}catch{return this.send(ws,{type:'error',error:'invalid_json'})}const st=this.states.get(ws)!;if(m.action==='ping')return this.send(ws,{type:'pong',at:new Date().toISOString()});if(m.action==='list')return this.send(ws,{type:'subscriptions',streamers:[...st.subs.keys()]});if(!['subscribe','unsubscribe'].includes(m.action))return this.send(ws,{type:'error',error:'unknown_action'});const ids=[...new Set((Array.isArray(m.streamers)?m.streamers:[]).filter(validId))] as string[];if(m.action==='subscribe'){if(st.subs.size+ids.filter(id=>!st.subs.has(id)).length>this.cfg.maxWsSubscriptions)return this.send(ws,{type:'error',error:'subscription_limit'});const filter=Array.isArray(m.events)?new Set<string>(m.events.map(String)):null;for(const id of ids){if(!st.subs.has(id))await this.service.pool.acquire(id);st.subs.set(id,filter)}this.send(ws,{type:'subscribed',streamers:ids,events:filter?[...filter]:null})}else{for(const id of ids)if(st.subs.delete(id))this.service.pool.release(id);this.send(ws,{type:'unsubscribed',streamers:ids})}}
 private broadcast(e:CanonicalEvent){for(const ws of this.wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const st=this.states.get(ws),filter=st?.subs.get(e.streamerId);if(filter===undefined)continue;if(filter&&!(filter.has(e.type)||filter.has(String(e.code))||filter.has(e.category)))continue;if(ws.bufferedAmount>this.cfg.wsBackpressureBytes){this.service.metrics.inc('soop_ws_backpressure_drops_total');continue}this.send(ws,{type:'event',event:e})}}
 private send(ws:WebSocket,data:any){try{ws.send(JSON.stringify(data))}catch{this.service.metrics.inc('soop_ws_send_errors_total')}}
 async close(){if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=undefined;for(const ws of this.wss.clients)try{ws.terminate()}catch{};await new Promise<void>(resolve=>{try{this.wss.close(()=>resolve())}catch{resolve()}})}
}
export function validId(id:any):id is string{return typeof id==='string'&&/^[A-Za-z0-9_-]{1,64}$/.test(id)}
