import type{EventCategory,EventDescriptor,EventSupportLevel}from'../types.js';
const c=(code:number,name:string,description:string,category:EventCategory,supportLevel:EventSupportLevel='stable',note?:string):EventDescriptor=>({code,name,description,category,supportLevel,...(note?{note}:{})});
export const EVENT_CATALOG:EventDescriptor[]=[
 c(0,'KEEP_ALIVE','Keep Alive','connection'),c(1,'LOGIN','Login Handshake','connection','conditional','Authentication/login handshake details vary by session mode.'),c(2,'JOIN_CHANNEL','Channel Join Handshake','connection'),
 c(3,'QUIT_CHANNEL','Channel Leave','viewer','conditional','Semantics depend on server quit status and may include forced exits.'),c(4,'CHAT_USER','Chat User Join/Leave','viewer'),c(5,'CHAT_MESSAGE','Chat Message','chat'),c(6,'SET_CHANNEL_NAME','Set Channel Name','system'),c(7,'SET_BJ_STAT','Set BJ Status','system'),c(8,'SET_DUMB','Chat Mute','moderation'),c(9,'DIRECT_CHAT','Direct Chat','chat','conditional','Requires authenticated/eligible session for send; receive visibility depends on session.'),
 c(10,'NOTICE','Notice','notification','conditional'),c(11,'KICK','Kick','moderation'),c(12,'SET_USER_FLAG','Set User Flag','system'),c(13,'SET_SUB_BJ','Set Sub BJ','system','conditional','May require broadcaster/manager context.'),c(14,'SET_NICKNAME','Set Nickname','system'),c(15,'SERVER_STAT','Server Status','system'),c(16,'NULL_16','Unused','system','raw-only'),c(17,'CLUB_COLOR','Club Color','system','conditional'),
 c(18,'SEND_BALLOON','Send Star Balloon','donation'),c(19,'ICE_MODE','Ice Mode','system'),c(20,'SEND_FAN_LETTER','Send Fan Letter','donation'),c(21,'ICE_MODE_EX','Extended Ice Mode','system'),c(22,'GET_ICE_MODE_RELAY','Get Ice Mode Relay','system','conditional'),c(23,'SLOW_MODE','Slow Mode','moderation'),c(24,'RELOAD_BURN_LEVEL','Reload Burn Level','system','conditional'),c(25,'BLIND_KICK','Blind Kick','moderation','conditional'),c(26,'MANAGER_CHAT','Manager Chat','chat','conditional','Visibility can depend on manager privileges.'),c(27,'APPEND_DATA','Append Data','system','raw-only'),
 c(28,'BASEBALL_EVENT','Baseball Event','notification','conditional'),c(29,'PAID_ITEM','Paid Item','item','conditional'),c(30,'TOP_FAN','Top Fan','notification','conditional'),c(31,'SNS_MESSAGE','SNS Message','chat','conditional'),c(32,'SNS_MODE','SNS Mode','system','conditional'),c(33,'SEND_BALLOON_SUB','Send Star Balloon (Sub)','donation'),c(34,'SEND_FAN_LETTER_SUB','Send Fan Letter (Sub)','donation'),c(35,'TOP_FAN_SUB','Top Fan (Sub)','notification','conditional'),c(36,'BJ_STICKER_ITEM','BJ Sticker Item','item','conditional'),c(37,'CHOCOLATE','Chocolate','donation'),c(38,'CHOCOLATE_SUB','Chocolate (Sub)','donation'),c(39,'TOP_CLAN','Top Clan','notification','conditional'),c(40,'TOP_CLAN_SUB','Top Clan (Sub)','notification','conditional'),c(41,'SUPER_CHAT','Super Chat','donation','conditional'),c(42,'UPDATE_TICKET','Update Ticket','item','conditional'),c(43,'NOTI_GAME_RANKER','Game Ranker Notification','notification','conditional'),c(44,'STAR_COIN','Star Coin','donation','conditional'),c(45,'SEND_QUICK_VIEW','Send Quick View Gift','item'),c(46,'ITEM_STATUS','Item Status','item','conditional'),c(47,'ITEM_USING','Item In Use','item','conditional'),c(48,'USE_QUICK_VIEW','Use Quick View','item','conditional'),
 c(50,'NOTIFY_POLL','Poll Notification','notification'),c(51,'CHAT_BLOCK_MODE','Chat Block Mode','moderation','conditional'),c(52,'UNCLASSIFIED_MODERATION_52','Unclassified privileged moderation signal','unknown','raw-only','Not exposed as a blacklist feature. The public/anonymous socket does not establish a readable broadcaster blacklist. Preserve RAW only.'),c(53,'SET_BROAD_INFO','Set Broadcast Info','system','conditional'),c(54,'BAN_WORD','Ban Word Setting','moderation','conditional','Visibility may depend on chat/manager context.'),c(58,'SEND_ADMIN_NOTICE','Send Admin Notice','notification','conditional'),
 c(65,'FREECAT_OWNER_JOIN','Freecat Owner Join','viewer','conditional'),c(70,'BUY_GOODS','Buy Goods','item'),c(71,'BUY_GOODS_SUB','Buy Goods (Sub)','item'),c(72,'SEND_PROMOTION','Send Promotion','notification','conditional'),c(74,'NOTIFY_VR','VR Notification','notification','conditional'),c(75,'NOTIFY_MOBBROAD_PAUSE','Mobile Broadcast Pause Notification','system'),c(76,'KICK_AND_CANCEL','Kick and Cancel','moderation','conditional'),c(77,'KICK_USERLIST','Kick User List','moderation','conditional','Administrative visibility can depend on privileges.'),c(78,'ADMIN_CHAT_USER','Admin Chat User','moderation','conditional','Administrative visibility can depend on privileges.'),c(79,'CLI_DOBAE_INFO','Spam Info','moderation','conditional'),
 c(86,'VOD_BALLOON','VOD Balloon','donation'),c(87,'ADCON_EFFECT','Adcon Effect','donation'),c(90,'KICK_MSG_STATE','Kick Message State','moderation','conditional'),c(91,'FOLLOW_ITEM','New Subscription','item'),c(92,'ITEM_SELL_EFFECT','Item Sell Effect','item','conditional'),c(93,'FOLLOW_ITEM_EFFECT','Continuous Subscription','item'),c(94,'TRANSLATION_STATE','Translation State','system','conditional'),c(95,'TRANSLATION','Translation','chat','conditional'),
 c(102,'GIFT_TICKET','Gift Ticket','donation'),c(103,'VOD_ADCON','VOD Adcon','donation','conditional'),c(104,'BJ_NOTICE','BJ Notice','notification'),c(105,'VIDEO_BALLOON','Video Donation','donation'),c(107,'STATION_ADCON','Station Adcon','donation'),c(108,'SEND_SUBSCRIPTION','Gift Subscription','donation'),c(109,'OGQ_EMOTICON','OGQ Emoticon','chat'),c(110,'EMOTICON_TICKET','Emoticon Ticket','item'),c(111,'ITEM_DROPS','Item Drops','item'),c(117,'VIDEO_BALLOON_LINK','Video Balloon Link','donation','conditional'),c(118,'OGQ_EMOTICON_GIFT','OGQ Emoticon Gift','donation'),c(119,'AD_IN_BROAD_JSON','In-Broadcast Ad JSON','notification','conditional'),c(120,'GEM_ITEM_SEND','Gem Item Send','donation'),c(121,'MISSION','Challenge Mission','notification'),c(122,'LIVE_CAPTION','Live Caption','notification'),c(125,'MISSION_SETTLE','Mission Settlement','notification'),c(126,'SET_ADMIN_FLAG','Set Admin Flag','moderation','conditional','Administrative visibility can depend on privileges.'),c(127,'CHUSER_EXTEND','Subscriber/User Extension','viewer','conditional','Do not interpret as a complete privileged user list without validating session context.'),c(128,'ADMIN_CHUSER_EXTEND','Admin Chat User Extended','moderation','conditional','Administrative visibility can depend on privileges.'),
 c(-2,'RAW','Raw Packet','unknown','raw-only'),c(-3,'DISCONNECTED','Disconnected','connection'),c(-4,'RECONNECTING','Reconnecting','connection'),c(-5,'RECONNECTED','Reconnected','connection'),c(-1,'NONE_TYPE','Unknown Type','unknown','raw-only')
];
export const EVENT_BY_CODE=new Map(EVENT_CATALOG.map(x=>[x.code,x]));
export function eventDescriptor(code:number):EventDescriptor{return EVENT_BY_CODE.get(code)??{code,name:`UNKNOWN_${code}`,description:'Unknown SOOP event',category:'unknown',supportLevel:'raw-only'}}
