import test from'node:test';import assert from'node:assert/strict';import http from'node:http';import{EventEmitter}from'node:events';import{existsSync}from'node:fs';
const hasWs=existsSync('node_modules/ws/index.js');
class FakePool extends EventEmitter{acquires=0;releases=0;delayMs=0;async acquire(){this.acquires++;if(this.delayMs)await new Promise(r=>setTimeout(r,this.delayMs));return{} as any}release(){this.releases++}}
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function runtime(){const [{default:WebSocket},{WsHub},{loadConfig}]=await Promise.all([import('ws'),import('../src/server/ws-hub.js'),import('../src/config.js')]);return{WebSocket,WsHub,loadConfig}}
async function setup(delayMs=0){const {WsHub,loadConfig}=await runtime(),pool=new FakePool();pool.delayMs=delayMs;const cfg={...loadConfig(),wsClientIdleMs:60000,maxWsClients:10,maxWsSubscriptions:10,wsReplayEvents:100};const hub=new WsHub({pool,metrics:{inc(){},set(){}}} as any,cfg as any),server=http.createServer();server.on('upgrade',(req,socket,head)=>hub.handleUpgrade(req,socket,head));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const a=server.address();if(!a||typeof a==='string')throw new Error('no address');const close=async()=>{await hub.close();await new Promise<void>(r=>server.close(()=>r()))};return{pool,url:`ws://127.0.0.1:${a.port}`,close}}
async function open(url:string){const {WebSocket}=await runtime(),ws=new WebSocket(url);await new Promise<void>((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject)});return ws}
test('serialized duplicate subscribe acquires a streamer only once',{skip:!hasWs},async()=>{const x=await setup();try{const ws=await open(x.url);ws.send(JSON.stringify({action:'subscribe',streamers:['abc']}));ws.send(JSON.stringify({action:'subscribe',streamers:['abc']}));await wait(40);assert.equal(x.pool.acquires,1);ws.close();await wait(30);assert.equal(x.pool.releases,1)}finally{await x.close()}});
test('socket closing while acquire is pending releases the acquired ref',{skip:!hasWs},async()=>{const x=await setup(60);try{const ws=await open(x.url);ws.send(JSON.stringify({action:'subscribe',streamers:['abc']}));for(let i=0;i<20&&x.pool.acquires===0;i++)await wait(5);assert.equal(x.pool.acquires,1);ws.terminate();await wait(100);assert.equal(x.pool.releases,1)}finally{await x.close()}});
