import type{ChannelSnapshot,LiveSnapshot,ProviderObservation}from'../types.js';
import{CircuitBreaker}from'../core/circuit-breaker.js';
import{PROVIDER_PROVENANCE}from'../core/provider-provenance.js';
import{withDeadline}from'../core/deadline.js';
import{broadcastId,normalizeViewPresets,nullableBoolean,nullableNumber,nullableString,selectViewBps}from'../http/normalize.js';

export class ReindeerProvider{
 readonly breaker:CircuitBreaker;private client:any;private init?:Promise<void>;
 constructor(private enabled:boolean,private timeoutMs:number){this.breaker=new CircuitBreaker('reindeer',enabled)}
 private async boot(){if(this.client)return;if(!this.init)this.init=(async()=>{const m:any=await import('soop-extension');this.client=new m.SoopClient()})();try{await withDeadline(this.init,this.timeoutMs,'reindeer boot')}catch(e){this.init=undefined;throw e}}
 private async observe<T>(fn:()=>Promise<T>):Promise<ProviderObservation<T>>{const s=Date.now(),requestStartedAt=new Date(s).toISOString();try{const value=await this.breaker.run(async()=>{await this.boot();return withDeadline(fn(),this.timeoutMs,'reindeer request')});const end=Date.now(),responseAt=new Date(end).toISOString();return{provider:'reindeer',ok:true,latencyMs:end-s,observedAt:responseAt,requestStartedAt,responseAt,sampleAgeMs:end-s,value,provenance:PROVIDER_PROVENANCE.reindeer}}catch(e){const end=Date.now(),responseAt=new Date(end).toISOString();return{provider:'reindeer',ok:false,latencyMs:end-s,observedAt:responseAt,requestStartedAt,responseAt,sampleAgeMs:end-s,error:e instanceof Error?e.message:String(e),provenance:PROVIDER_PROVENANCE.reindeer}}}
 live(id:string){return this.observe<LiveSnapshot>(async()=>{const j:any=await this.client.live.detail(id),x=j?.CHANNEL??{},bno=broadcastId(x.BNO),bitrate=nullableNumber(x.BPS),viewPresets=normalizeViewPresets(x.VIEWPRESET);return{streamerId:id,online:(nullableNumber(x.RESULT)??0)!==0&&Boolean(bno),bno,previousBno:broadcastId(x.PBNO),chatNo:broadcastId(x.CHATNO),streamerNickname:nullableString(x.BJNICK),title:nullableString(x.TITLE),category:nullableString(x.CATE),viewerCount:nullableNumber(x.CTUSER),startedSecondsAgo:nullableNumber(x.BTIME),passwordProtected:nullableBoolean(x.BPWD),resolution:nullableString(x.RESOLUTION),bitrate,viewPresets,selectedViewBps:selectViewBps(viewPresets,bitrate),lowLatency:nullableBoolean(x.LOWLAYTENCYBJ),channelDomain:nullableString(x.CHDOMAIN),channelPort:nullableNumber(x.CHPT),ftk:nullableString(x.FTK),geoCountryCode:nullableString(x.geo_cc),geoRegionCode:nullableString(x.geo_rc),acceptLanguage:nullableString(x.acpt_lang),serviceLanguage:nullableString(x.svc_lang),raw:j}})}
 channel(id:string){return this.observe<ChannelSnapshot>(async()=>{const j:any=await this.client.channel.station(id),s=j?.station??{},b=j?.broad??{},u=s?.upd??j?.upd??{},bn=nullableNumber(b.broad_no),broadNo=bn!==undefined&&Number.isInteger(bn)&&bn>0?bn:undefined;return{streamerId:id,nickname:nullableString(s.user_nick),stationName:nullableString(s.station_name),stationTitle:nullableString(s.station_title),profileImage:nullableString(j?.profile_image),favorites:nullableNumber(u.fan_cnt),subscribers:nullableNumber(j?.subscription?.total),totalViewCount:nullableNumber(u.total_view_cnt),currentViewerCount:nullableNumber(b.current_sum_viewer),broadNo,broadTitle:nullableString(b.broad_title),isPassword:nullableBoolean(b.is_password),raw:j}})}
}
