import type{ChannelSnapshot,FieldConsensusMeta,LiveSnapshot,ProviderName,ProviderObservation,UnifiedResult}from'../types.js';

type WeightResolver=(provider:ProviderName,observation:ProviderObservation<unknown>)=>number;
const fallbackWeights:Record<ProviderName,number>={native:1,reindeer:.9,soopapi:.97,soop4j:.9,soopjs:.55};
const weightOf=(o:ProviderObservation<unknown>,resolver?:WeightResolver)=>Math.max(.01,resolver?resolver(o.provider,o):fallbackWeights[o.provider]);
const median=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);if(!a.length)return undefined;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const weightedMedian=(items:Array<{value:number;weight:number}>)=>{const a=[...items].sort((x,y)=>x.value-y.value),total=a.reduce((s,x)=>s+x.weight,0);let c=0;for(const x of a){c+=x.weight;if(c>=total/2)return x.value}return a.at(-1)?.value};
const sourcePick=<T>(o:ProviderObservation<T>[],resolver?:WeightResolver)=>o.filter(x=>x.ok&&x.value).sort((a,b)=>weightOf(b as any,resolver)-weightOf(a as any,resolver))[0];
const groups=<T>(good:Array<ProviderObservation<T>>)=>({implementationGroups:new Set(good.map(x=>x.provenance?.independenceGroup??x.provider)).size,upstreamFamilies:new Set(good.map(x=>x.provenance?.upstreamFamily??x.provider)).size});

function robustViewer<T>(good:Array<ProviderObservation<T>&{value:T}>,field:(v:T)=>number|undefined,resolver?:WeightResolver){const raw=good.map(o=>({provider:o.provider,value:field(o.value),weight:weightOf(o as any,resolver)})).filter((x):x is {provider:ProviderName;value:number;weight:number}=>Number.isFinite(x.value));if(!raw.length)return{value:undefined,outliers:[] as ProviderName[],agreement:0,sources:[] as ProviderName[]};if(raw.length<3){const v=weightedMedian(raw),spread=raw.length>1?Math.abs(raw[0].value-raw[1].value)/Math.max(1,Math.abs(v??1)):0;return{value:v,outliers:[],agreement:Math.max(0,1-Math.min(1,spread)),sources:raw.map(x=>x.provider)}}const m=median(raw.map(x=>x.value))!,dev=raw.map(x=>Math.abs(x.value-m)),mad=median(dev)??0,tolerance=mad>0?Math.max(5,mad*4):Math.max(20,Math.abs(m)*.2),kept=raw.filter(x=>Math.abs(x.value-m)<=tolerance),outliers=raw.filter(x=>Math.abs(x.value-m)>tolerance).map(x=>x.provider),v=weightedMedian(kept.length?kept:raw),total=raw.reduce((s,x)=>s+x.weight,0),agree=(kept.length?kept:raw).reduce((s,x)=>s+x.weight,0)/(total||1);return{value:v,outliers,agreement:agree,sources:(kept.length?kept:raw).map(x=>x.provider)}}

function discreteField<T>(good:Array<ProviderObservation<T>&{value:T}>,field:(v:T)=>unknown,resolver?:WeightResolver):{value:unknown;meta:FieldConsensusMeta}|undefined{const rows=good.map(o=>({provider:o.provider,value:field(o.value),weight:weightOf(o as any,resolver)})).filter(x=>x.value!==undefined&&x.value!==null&&x.value!=='');if(!rows.length)return;const buckets=new Map<string,{value:unknown,weight:number,sources:ProviderName[]}>();for(const r of rows){const norm=typeof r.value==='string'?r.value.trim():JSON.stringify(r.value),k=String(norm);const b=buckets.get(k)??{value:r.value,weight:0,sources:[]};b.weight+=r.weight;b.sources.push(r.provider);buckets.set(k,b)}const ordered=[...buckets.values()].sort((a,b)=>b.weight-a.weight),win=ordered[0],total=rows.reduce((s,x)=>s+x.weight,0),winners=new Set(win.sources);return{value:win.value,meta:{value:win.value,agreement:total?win.weight/total:0,sourceCount:rows.length,sources:win.sources,conflictingProviders:rows.filter(x=>!winners.has(x.provider)).map(x=>x.provider)}}}

function confidence<T>(good:Array<ProviderObservation<T>>,agreement:number,totalWeight:number,status:'confirmed'|'uncertain'|'single-source'){const maxExpected=3.2,weightFactor=Math.min(1,totalWeight/maxExpected),g=groups(good),implFactor=Math.min(1,g.implementationGroups/3),upstreamFactor=Math.min(1,.55+.2*Math.max(0,g.upstreamFamilies-1));let c=.08+weightFactor*.34+agreement*.34+implFactor*.16+upstreamFactor*.08;if(status==='single-source')c=Math.min(c,.55);if(status==='uncertain')c=Math.min(c,.49);return Math.max(.05,Math.min(.999,c))}

export function liveConsensus(o:ProviderObservation<LiveSnapshot>[],resolver?:WeightResolver):UnifiedResult<LiveSnapshot>{const good=o.filter(x=>x.ok&&x.value) as Array<ProviderObservation<LiveSnapshot>&{value:LiveSnapshot}>;if(!good.length)throw new Error('All live providers failed');const p=sourcePick(o,resolver)!;const base={...p.value!};const onlineWeight=good.filter(x=>x.value.online).reduce((s,x)=>s+weightOf(x as any,resolver),0),offlineWeight=good.filter(x=>!x.value.online).reduce((s,x)=>s+weightOf(x as any,resolver),0),totalWeight=onlineWeight+offlineWeight,margin=totalWeight?Math.abs(onlineWeight-offlineWeight)/totalWeight:0,single=good.length===1,uncertain=!single&&margin<.18,onlineState=uncertain?'uncertain':onlineWeight>=offlineWeight?'online':'offline';if(!uncertain)base.online=onlineState==='online';const viewer=robustViewer(good,v=>v.viewerCount,resolver);if(viewer.value!==undefined)base.viewerCount=viewer.value;const winningWeight=Math.max(onlineWeight,offlineWeight),agreement=totalWeight?winningWeight/totalWeight:0,status=single?'single-source':uncertain?'uncertain':'confirmed',g=groups(good);return{data:base,confidence:confidence(good,agreement,totalWeight,status),source:p.provider,corroboratedBy:good.filter(x=>x.provider!==p.provider&&(!uncertain&&x.value.online===base.online)).map(x=>x.provider),observations:o,observedAt:new Date().toISOString(),consensus:{status,onlineState,agreement,totalWeight,winningWeight,sourceCount:good.length,implementationGroups:g.implementationGroups,upstreamFamilies:g.upstreamFamilies,reason:uncertain?'provider votes are too close to call safely':single?'only one provider returned usable data':undefined,outlierProviders:viewer.outliers,fields:{online:{value:uncertain?undefined:base.online,agreement,sourceCount:good.length,sources:good.filter(x=>uncertain||x.value.online===base.online).map(x=>x.provider),conflictingProviders:uncertain?good.map(x=>x.provider):good.filter(x=>x.value.online!==base.online).map(x=>x.provider)},viewerCount:{value:viewer.value,agreement:viewer.agreement,sourceCount:viewer.sources.length,sources:viewer.sources,conflictingProviders:viewer.outliers}}}}}

export function channelConsensus(o:ProviderObservation<ChannelSnapshot>[],resolver?:WeightResolver):UnifiedResult<ChannelSnapshot>{const good=o.filter(x=>x.ok&&x.value) as Array<ProviderObservation<ChannelSnapshot>&{value:ChannelSnapshot}>;if(!good.length)throw new Error('All channel providers failed');const p=sourcePick(o,resolver)!,base={...p.value!},fields:Record<string,FieldConsensusMeta>={};const viewer=robustViewer(good,v=>v.currentViewerCount,resolver);if(viewer.value!==undefined){base.currentViewerCount=viewer.value;fields.currentViewerCount={value:viewer.value,agreement:viewer.agreement,sourceCount:viewer.sources.length,sources:viewer.sources,conflictingProviders:viewer.outliers}}for(const [key,getter] of [
 ['nickname',(v:ChannelSnapshot)=>v.nickname],['stationName',(v:ChannelSnapshot)=>v.stationName],['stationTitle',(v:ChannelSnapshot)=>v.stationTitle],['profileImage',(v:ChannelSnapshot)=>v.profileImage],['broadNo',(v:ChannelSnapshot)=>v.broadNo],['broadTitle',(v:ChannelSnapshot)=>v.broadTitle],['isPassword',(v:ChannelSnapshot)=>v.isPassword]
] as const){const r=discreteField(good,getter,resolver);if(r){(base as any)[key]=r.value;fields[key]=r.meta}}
const totalWeight=good.reduce((s,x)=>s+weightOf(x as any,resolver),0),agreements=Object.values(fields).map(x=>x.agreement).filter(Number.isFinite),agreement=agreements.length?agreements.reduce((a,b)=>a+b,0)/agreements.length:(good.length>1?.75:.7),strongConflicts=Object.values(fields).filter(x=>x.sourceCount>1&&x.agreement<.6).length,status=good.length===1?'single-source':strongConflicts?'uncertain':'confirmed',g=groups(good);return{data:base,confidence:confidence(good,agreement,totalWeight,status),source:p.provider,corroboratedBy:good.filter(x=>x.provider!==p.provider).map(x=>x.provider),observations:o,observedAt:new Date().toISOString(),consensus:{status,agreement,totalWeight,winningWeight:totalWeight*agreement,sourceCount:good.length,implementationGroups:g.implementationGroups,upstreamFamilies:g.upstreamFamilies,reason:good.length===1?'only one provider returned usable data':strongConflicts?`${strongConflicts} channel fields disagree materially`:undefined,outlierProviders:viewer.outliers,fields}}}
