import type{ChannelSnapshot,FieldConsensusMeta,FieldImportance,LiveSnapshot,ProviderName,ProviderObservation,UnifiedResult}from'../types.js';

type WeightResolver=(provider:ProviderName,observation:ProviderObservation<unknown>)=>number;
const fallbackWeights:Record<ProviderName,number>={native:1,reindeer:.9,soopapi:.97,soop4j:.9,soopjs:.55};
const importanceWeight:Record<FieldImportance,number>={critical:4,high:3,medium:2,low:1};
const baseWeight=(o:ProviderObservation<unknown>,resolver?:WeightResolver)=>Math.max(.01,resolver?resolver(o.provider,o):fallbackWeights[o.provider]);
const familyOf=(o:ProviderObservation<unknown>)=>o.provenance?.upstreamFamily??o.provider;
const midpoint=(o:ProviderObservation<unknown>)=>{const a=Date.parse(o.requestStartedAt??o.observedAt),b=Date.parse(o.responseAt??o.observedAt);return Number.isFinite(a)&&Number.isFinite(b)?a+(b-a)/2:Date.parse(o.observedAt)};
const temporalSkew=<T>(rows:ProviderObservation<T>[])=>{const xs=rows.map(x=>midpoint(x as any)).filter(Number.isFinite);return xs.length>1?Math.max(...xs)-Math.min(...xs):0};
const effectiveWeight=(o:ProviderObservation<unknown>,freshest:number,resolver?:WeightResolver)=>{const at=midpoint(o),lag=Number.isFinite(at)?Math.max(0,freshest-at):0,timeFactor=1/(1+lag/5000);return baseWeight(o,resolver)*timeFactor};
const median=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);if(!a.length)return undefined;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const weightedMedian=(items:Array<{value:number;weight:number}>)=>{const a=[...items].sort((x,y)=>x.value-y.value),total=a.reduce((s,x)=>s+x.weight,0);let c=0;for(const x of a){c+=x.weight;if(c>=total/2)return x.value}return a.at(-1)?.value};
const normalizeKey=(v:unknown)=>typeof v==='string'?v.trim():JSON.stringify(v);
const groups=<T>(good:Array<ProviderObservation<T>>)=>({implementationGroups:new Set(good.map(x=>x.provenance?.independenceGroup??x.provider)).size,upstreamFamilies:new Set(good.map(x=>familyOf(x as any))).size});

interface FamilyVote{family:string;value:unknown;weight:number;agreement:number;sources:ProviderName[];conflicts:ProviderName[]}
function familyDiscrete<T>(good:Array<ProviderObservation<T>&{value:T}>,field:(v:T)=>unknown,resolver?:WeightResolver):FamilyVote[]{
 const fresh=Math.max(...good.map(x=>midpoint(x as any)).filter(Number.isFinite),Date.now());
 const families=new Map<string,Array<{provider:ProviderName,value:unknown,weight:number}>>();
 for(const o of good){const value=field(o.value);if(value===undefined||value===null||value==='')continue;const family=familyOf(o as any),a=families.get(family)??[];a.push({provider:o.provider,value,weight:effectiveWeight(o as any,fresh,resolver)});families.set(family,a)}
 const out:FamilyVote[]=[];
 for(const[family,rows]of families){const buckets=new Map<string,{value:unknown,weight:number,sources:ProviderName[]}>();for(const r of rows){const k=String(normalizeKey(r.value)),b=buckets.get(k)??{value:r.value,weight:0,sources:[]};b.weight+=r.weight;b.sources.push(r.provider);buckets.set(k,b)}const ordered=[...buckets.values()].sort((a,b)=>b.weight-a.weight),win=ordered[0],total=rows.reduce((s,x)=>s+x.weight,0),agreement=total?win.weight/total:0;out.push({family,value:win.value,weight:Math.max(...rows.map(x=>x.weight))*Math.max(.15,agreement),agreement,sources:win.sources,conflicts:rows.filter(x=>!win.sources.includes(x.provider)).map(x=>x.provider)})}
 return out;
}

function fieldConfidence(agreement:number,families:number,sourceCount:number,skewMs:number,status:'confirmed'|'uncertain'|'single-source'){
 const independence=families<=1?.62:families===2?.9:1,source=Math.min(1,.55+.12*Math.max(0,sourceCount-1)),time=1/(1+Math.max(0,skewMs-500)/8000);let c=(agreement*.55+independence*.3+source*.15)*time;if(families<=1)c=Math.min(c,.86);if(status==='single-source')c=Math.min(c,.55);if(status==='uncertain')c=Math.min(c,.49);return Math.max(.03,Math.min(.999,c));
}

function discreteField<T>(good:Array<ProviderObservation<T>&{value:T}>,field:(v:T)=>unknown,importance:FieldImportance,resolver?:WeightResolver):{value:unknown;meta:FieldConsensusMeta}|undefined{
 const votes=familyDiscrete(good,field,resolver);if(!votes.length)return;
 const buckets=new Map<string,{value:unknown,weight:number,votes:FamilyVote[]}>();for(const v of votes){const k=String(normalizeKey(v.value)),b=buckets.get(k)??{value:v.value,weight:0,votes:[]};b.weight+=v.weight;b.votes.push(v);buckets.set(k,b)}const ordered=[...buckets.values()].sort((a,b)=>b.weight-a.weight),win=ordered[0],total=votes.reduce((s,x)=>s+x.weight,0),outer=total?win.weight/total:0,internal=win.votes.length?win.votes.reduce((s,x)=>s+x.agreement*x.weight,0)/(win.weight||1):0,agreement=outer*internal,sources=win.votes.flatMap(x=>x.sources),conflictingProviders=[...new Set([...win.votes.flatMap(x=>x.conflicts),...votes.filter(x=>!win.votes.includes(x)).flatMap(x=>[...x.sources,...x.conflicts])])],skew=temporalSkew(good),status=sources.length===1?'single-source':agreement<.6?'uncertain':'confirmed';
 return{value:win.value,meta:{value:win.value,agreement,confidence:fieldConfidence(agreement,votes.length,sources.length,skew,status),sourceCount:sources.length,sources,conflictingProviders,upstreamFamilies:votes.length,temporalSkewMs:skew,importance}};
}

function robustNumber<T>(good:Array<ProviderObservation<T>&{value:T}>,field:(v:T)=>number|undefined,importance:FieldImportance,resolver?:WeightResolver){
 const fresh=Math.max(...good.map(x=>midpoint(x as any)).filter(Number.isFinite),Date.now());let rows=good.map(o=>({o,provider:o.provider,family:familyOf(o as any),value:field(o.value),weight:effectiveWeight(o as any,fresh,resolver)})).filter((x):x is typeof x&{value:number}=>Number.isFinite(x.value));if(!rows.length)return undefined;
 const m=median(rows.map(x=>x.value))!,mad=median(rows.map(x=>Math.abs(x.value-m)))??0,tolerance=rows.length>=3?(mad>0?Math.max(5,mad*4):Math.max(20,Math.abs(m)*.2)):Infinity,outliers=rows.filter(x=>Math.abs(x.value-m)>tolerance).map(x=>x.provider);rows=rows.filter(x=>Math.abs(x.value-m)<=tolerance);if(!rows.length)return undefined;
 const fam=new Map<string,typeof rows>();for(const r of rows){const a=fam.get(r.family)??[];a.push(r);fam.set(r.family,a)}const familyRows=[...fam.entries()].map(([family,a])=>({family,value:weightedMedian(a.map(x=>({value:x.value,weight:x.weight})))!,weight:Math.max(...a.map(x=>x.weight)),sources:a.map(x=>x.provider)}));const value=weightedMedian(familyRows.map(x=>({value:x.value,weight:x.weight})))!;
 const relSpread=rows.length>1?(Math.max(...rows.map(x=>x.value))-Math.min(...rows.map(x=>x.value)))/Math.max(1,Math.abs(value)):0,spreadAgreement=Math.max(0,1-Math.min(1,relSpread/.25));const distanceAgreement=familyRows.reduce((s,x)=>s+x.weight*Math.max(0,1-Math.min(1,Math.abs(x.value-value)/Math.max(5,Math.abs(value)*.2))),0)/(familyRows.reduce((s,x)=>s+x.weight,0)||1),agreement=Math.min(spreadAgreement,distanceAgreement),sources=familyRows.flatMap(x=>x.sources),skew=temporalSkew(good),status=sources.length===1?'single-source':agreement<.55?'uncertain':'confirmed';
 return{value,outliers,meta:{value,agreement,confidence:fieldConfidence(agreement,familyRows.length,sources.length,skew,status),sourceCount:sources.length,sources,conflictingProviders:outliers,upstreamFamilies:familyRows.length,temporalSkewMs:skew,importance} satisfies FieldConsensusMeta};
}

const sourcePick=<T>(o:ProviderObservation<T>[],resolver?:WeightResolver)=>{const good=o.filter(x=>x.ok&&x.value);const freshest=Math.max(...good.map(x=>midpoint(x as any)).filter(Number.isFinite),Date.now());return good.sort((a,b)=>effectiveWeight(b as any,freshest,resolver)-effectiveWeight(a as any,freshest,resolver))[0]};
function overall(fields:Record<string,FieldConsensusMeta>,good:ProviderObservation<unknown>[],status:'confirmed'|'uncertain'|'single-source'){
 const rows=Object.values(fields);let sum=0,w=0,confidenceSum=0;for(const f of rows){const fw=importanceWeight[f.importance??'medium'];sum+=f.agreement*fw;confidenceSum+=(f.confidence??f.agreement)*fw;w+=fw}const agreement=w?sum/w:0,confidence=w?confidenceSum/w:0,g=groups(good),skew=temporalSkew(good);let c=confidence;if(g.upstreamFamilies<=1)c=Math.min(c,.86);if(status==='single-source')c=Math.min(c,.55);if(status==='uncertain')c=Math.min(c,.49);return{agreement,confidence:Math.max(.03,Math.min(.999,c)),g,skew};
}

export function liveConsensus(o:ProviderObservation<LiveSnapshot>[],resolver?:WeightResolver):UnifiedResult<LiveSnapshot>{
 const good=o.filter(x=>x.ok&&x.value) as Array<ProviderObservation<LiveSnapshot>&{value:LiveSnapshot}>;if(!good.length)throw new Error('All live providers failed');const p=sourcePick(o,resolver)!;const base={...p.value!},fields:Record<string,FieldConsensusMeta>={};
 const specs:Array<[keyof LiveSnapshot,(v:LiveSnapshot)=>unknown,FieldImportance]>=[['online',v=>v.online,'critical'],['bno',v=>v.bno,'critical'],['chatNo',v=>v.chatNo,'high'],['streamerNickname',v=>v.streamerNickname,'medium'],['title',v=>v.title,'medium'],['category',v=>v.category,'medium'],['passwordProtected',v=>v.passwordProtected,'high'],['resolution',v=>v.resolution,'low'],['channelDomain',v=>v.channelDomain,'high'],['channelPort',v=>v.channelPort,'high'],['lowLatency',v=>v.lowLatency,'low']];
 for(const[key,getter,importance]of specs){const r=discreteField(good,getter,importance,resolver);if(r){(base as any)[key]=r.value;fields[String(key)]=r.meta}}
 for(const[key,getter,importance]of [['viewerCount',(v:LiveSnapshot)=>v.viewerCount,'high'],['bitrate',(v:LiveSnapshot)=>v.bitrate,'low'],['selectedViewBps',(v:LiveSnapshot)=>v.selectedViewBps,'low']] as Array<[keyof LiveSnapshot,(v:LiveSnapshot)=>number|undefined,FieldImportance]>){const r=robustNumber(good,getter,importance,resolver);if(r){(base as any)[key]=r.value;fields[String(key)]=r.meta}}
 const online=fields.online,onlineState=!online||online.agreement<.6?'uncertain':base.online?'online':'offline',identityConflict=Boolean(fields.bno?.conflictingProviders?.length)&&Boolean((fields.bno?.agreement??1)<.85),single=good.length===1,status=single?'single-source':identityConflict||onlineState==='uncertain'?'uncertain':'confirmed',ov=overall(fields,good as any,status),outliers=[...new Set(Object.values(fields).flatMap(x=>x.conflictingProviders??[]))];
 const corroboratedBy=good.filter(x=>x.provider!==p.provider&&(fields.online?.sources.includes(x.provider)??true)&&(!base.bno||(fields.bno?.sources.includes(x.provider)??false))).map(x=>x.provider);return{data:base,confidence:ov.confidence,source:p.provider,corroboratedBy,observations:o,observedAt:new Date().toISOString(),consensus:{status,onlineState,agreement:ov.agreement,totalWeight:good.reduce((s,x)=>s+baseWeight(x as any,resolver),0),winningWeight:good.reduce((s,x)=>s+baseWeight(x as any,resolver),0)*ov.agreement,sourceCount:good.length,implementationGroups:ov.g.implementationGroups,upstreamFamilies:ov.g.upstreamFamilies,temporalSkewMs:ov.skew,reason:status==='uncertain'?'critical live evidence disagrees or is temporally ambiguous':single?'only one provider returned usable data':undefined,outlierProviders:outliers,fields}};
}

export function channelConsensus(o:ProviderObservation<ChannelSnapshot>[],resolver?:WeightResolver):UnifiedResult<ChannelSnapshot>{
 const good=o.filter(x=>x.ok&&x.value) as Array<ProviderObservation<ChannelSnapshot>&{value:ChannelSnapshot}>;if(!good.length)throw new Error('All channel providers failed');const p=sourcePick(o,resolver)!,base={...p.value!},fields:Record<string,FieldConsensusMeta>={};
 const discrete:Array<[keyof ChannelSnapshot,(v:ChannelSnapshot)=>unknown,FieldImportance]>=[['nickname',v=>v.nickname,'medium'],['stationName',v=>v.stationName,'medium'],['stationTitle',v=>v.stationTitle,'medium'],['profileImage',v=>v.profileImage,'low'],['broadNo',v=>v.broadNo,'critical'],['broadTitle',v=>v.broadTitle,'medium'],['isPassword',v=>v.isPassword,'high']];for(const[key,getter,importance]of discrete){const r=discreteField(good,getter,importance,resolver);if(r){(base as any)[key]=r.value;fields[String(key)]=r.meta}}
 for(const[key,getter,importance]of [['currentViewerCount',(v:ChannelSnapshot)=>v.currentViewerCount,'high'],['favorites',(v:ChannelSnapshot)=>v.favorites,'low'],['subscribers',(v:ChannelSnapshot)=>v.subscribers,'low'],['totalViewCount',(v:ChannelSnapshot)=>v.totalViewCount,'low']] as Array<[keyof ChannelSnapshot,(v:ChannelSnapshot)=>number|undefined,FieldImportance]>){const r=robustNumber(good,getter,importance,resolver);if(r){(base as any)[key]=r.value;fields[String(key)]=r.meta}}
 const identityConflict=Boolean(fields.broadNo?.conflictingProviders?.length)&&Boolean((fields.broadNo?.agreement??1)<.85),strongConflicts=Object.values(fields).filter(f=>f.importance!=='low'&&f.sourceCount>1&&f.agreement<.5).length,single=good.length===1,status=single?'single-source':identityConflict||strongConflicts?'uncertain':'confirmed',ov=overall(fields,good as any,status),outliers=[...new Set(Object.values(fields).flatMap(x=>x.conflictingProviders??[]))];const corroboratedBy=good.filter(x=>x.provider!==p.provider&&(!base.broadNo||(fields.broadNo?.sources.includes(x.provider)??false))).map(x=>x.provider);return{data:base,confidence:ov.confidence,source:p.provider,corroboratedBy,observations:o,observedAt:new Date().toISOString(),consensus:{status,agreement:ov.agreement,totalWeight:good.reduce((s,x)=>s+baseWeight(x as any,resolver),0),winningWeight:good.reduce((s,x)=>s+baseWeight(x as any,resolver),0)*ov.agreement,sourceCount:good.length,implementationGroups:ov.g.implementationGroups,upstreamFamilies:ov.g.upstreamFamilies,temporalSkewMs:ov.skew,reason:single?'only one provider returned usable data':status==='uncertain'?'important channel fields disagree materially':undefined,outlierProviders:outliers,fields}};
}
