import{randomUUID}from'node:crypto';import type{CanonicalEvent,ProtocolAnomaly,ProtocolDriftIncident}from'../types.js';
interface TimedEvent{at:number;streamerId:string;unknown:boolean;code:number}
interface TimedAnomaly{at:number;anomaly:ProtocolAnomaly;malformed:boolean}
export interface DriftConfig{windowMs:number;minUnknown:number;minMalformed:number;minStreams:number;unknownRatio:number;alertCooldownMs:number}

/** Rolling-window drift detector. Hot-path updates are O(1); expensive materialization happens only on incident/snapshot. */
export class ProtocolDriftDetector{
 private events:TimedEvent[]=[];private eventHead=0;private anomalies:TimedAnomaly[]=[];private anomalyHead=0;private incidents:ProtocolDriftIncident[]=[];private lastAlertAt=0;
 private totalEvents=0;private unknownEvents=0;private malformedPackets=0;private unknownCodes=new Map<number,number>();private affectedStreams=new Map<string,number>();
 constructor(private cfg:DriftConfig,private maxEvents=100000,private maxAnomalies=20000){}
 private bump<K>(m:Map<K,number>,k:K,delta:number){const n=(m.get(k)??0)+delta;if(n<=0)m.delete(k);else m.set(k,n)}
 observeEvent(e:CanonicalEvent){const at=Date.parse(e.receivedAt)||Date.now(),unknown=e.category==='unknown';this.events.push({at,streamerId:e.streamerId,unknown,code:e.code});this.totalEvents++;if(unknown){this.unknownEvents++;this.bump(this.unknownCodes,e.code,1);this.bump(this.affectedStreams,e.streamerId,1)}this.prune(at);this.cap();return this.evaluate(at)}
 observeAnomaly(anomaly:ProtocolAnomaly){const at=Date.parse(anomaly.receivedAt)||Date.now(),malformed=['parse-error','length-mismatch'].includes(anomaly.kind);this.anomalies.push({at,anomaly,malformed});if(malformed){this.malformedPackets++;this.bump(this.affectedStreams,anomaly.streamerId,1)}this.prune(at);this.cap();return this.evaluate(at)}
 private prune(now:number){const cutoff=now-this.cfg.windowMs;while(this.eventHead<this.events.length&&this.events[this.eventHead].at<cutoff){const x=this.events[this.eventHead++];this.totalEvents--;if(x.unknown){this.unknownEvents--;this.bump(this.unknownCodes,x.code,-1);this.bump(this.affectedStreams,x.streamerId,-1)}}while(this.anomalyHead<this.anomalies.length&&this.anomalies[this.anomalyHead].at<cutoff){const x=this.anomalies[this.anomalyHead++];if(x.malformed){this.malformedPackets--;this.bump(this.affectedStreams,x.anomaly.streamerId,-1)}}if(this.eventHead>4096&&this.eventHead>this.events.length/2){this.events=this.events.slice(this.eventHead);this.eventHead=0}if(this.anomalyHead>2048&&this.anomalyHead>this.anomalies.length/2){this.anomalies=this.anomalies.slice(this.anomalyHead);this.anomalyHead=0}}
 private cap(){while(this.events.length-this.eventHead>this.maxEvents){const x=this.events[this.eventHead++];this.totalEvents--;if(x.unknown){this.unknownEvents--;this.bump(this.unknownCodes,x.code,-1);this.bump(this.affectedStreams,x.streamerId,-1)}}while(this.anomalies.length-this.anomalyHead>this.maxAnomalies){const x=this.anomalies[this.anomalyHead++];if(x.malformed){this.malformedPackets--;this.bump(this.affectedStreams,x.anomaly.streamerId,-1)}}}
 private evaluate(now:number){if(now-this.lastAlertAt<this.cfg.alertCooldownMs)return undefined;const ratio=this.totalEvents?this.unknownEvents/this.totalEvents:0,streamCount=this.affectedStreams.size;let reason:ProtocolDriftIncident['reason']|undefined,severity:ProtocolDriftIncident['severity']='medium';if(this.unknownEvents>=this.cfg.minUnknown&&streamCount>=this.cfg.minStreams&&ratio>=this.cfg.unknownRatio){reason='unknown-rate';severity=ratio>=Math.max(.2,this.cfg.unknownRatio*2)?'high':'medium'}else if(this.malformedPackets>=this.cfg.minMalformed&&streamCount>=this.cfg.minStreams){reason='malformed-rate';severity=this.malformedPackets>=this.cfg.minMalformed*2?'high':'medium'}if(!reason)return;const streamIds=[...this.affectedStreams.keys()],incident:ProtocolDriftIncident={id:randomUUID(),startedAt:new Date(Math.max(0,now-this.cfg.windowMs)).toISOString(),detectedAt:new Date(now).toISOString(),severity,reason,windowMs:this.cfg.windowMs,totalEvents:this.totalEvents,unknownEvents:this.unknownEvents,malformedPackets:this.malformedPackets,affectedStreams:streamCount,unknownRatio:ratio,sampleCodes:[...this.unknownCodes.keys()].slice(0,20),sampleSignatures:[...new Set(this.anomalies.slice(this.anomalyHead).map(x=>x.anomaly.signature).filter((x):x is string=>Boolean(x)))].slice(0,20),sampleStreams:streamIds.slice(0,20)};this.incidents.push(incident);if(this.incidents.length>100)this.incidents.shift();this.lastAlertAt=now;return incident}
 snapshot(){this.prune(Date.now());return{windowMs:this.cfg.windowMs,totalEvents:this.totalEvents,unknownEvents:this.unknownEvents,unknownRatio:this.totalEvents?this.unknownEvents/this.totalEvents:0,malformedPackets:this.malformedPackets,affectedStreams:this.affectedStreams.size,lastIncident:this.incidents.at(-1)}}
 listIncidents(){return[...this.incidents].reverse()}
}
