const $=s=>document.querySelector(s);const nf=new Intl.NumberFormat('ko-KR');const STORE='m4-donation-live-v1';const BASE_STORE='m4-donation-api-base-v1';
let data,liveEvents=[],socket=null,retryTimer=null,pingTimer=null,watchTimer=null,lastSeq=0,connectionRequested=false,page=1,pageSize=40,filters={day:'all',kind:'all',query:''},addedIds=new Set();
const kindNames={'별풍선':'별풍선','애드벌룬':'애드벌룬','영상풍선':'영상풍선','VOD':'VOD','star_balloon':'별풍선','star':'별풍선','balloon':'별풍선','ad_balloon':'애드벌룬','adcon':'애드벌룬','video_balloon':'영상풍선','vod_balloon':'VOD 후원','challenge_mission':'도전미션','battle_mission':'대결미션','fan_letter':'팬레터','chocolate':'초콜릿','gift_ticket':'선물권','subscription':'구독 선물'};
const kindLabel=k=>kindNames[k]||String(k||'후원');const fmt=n=>nf.format(Math.round(Number(n)||0));
async function init(){try{data=await fetch('./data.json').then(r=>{if(!r.ok)throw Error('기록 파일을 열 수 없습니다');return r.json()})}catch(e){$('#apiNotice').textContent=e.message;return}
 try{liveEvents=JSON.parse(localStorage.getItem(STORE)||'[]');if(!Array.isArray(liveEvents))liveEvents=[]}catch{liveEvents=[]}liveEvents=liveEvents.slice(-5000);liveEvents.forEach(e=>e.eventId&&addedIds.add(e.eventId));lastSeq=Number(localStorage.getItem(STORE+':seq')||0)||0;
 const saved=localStorage.getItem(BASE_STORE);$('#apiBase').value=saved||'http://localhost:8080';renderAll();$('#connectBtn').addEventListener('click',()=>connectionRequested?disconnect():connect());$('#apiBase').addEventListener('keydown',e=>{if(e.key==='Enter')connect()});$('#apiBase').addEventListener('change',()=>{const v=cleanBase($('#apiBase').value);if(v){localStorage.setItem(BASE_STORE,v);$('#apiBase').value=v}});$('#settingsBtn').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=$('#closeHelp2').onclick=()=>$('#helpDialog').close();$('#clearLive').onclick=clearLive;$('#searchInput').oninput=e=>{filters.query=e.target.value.trim().toLowerCase();page=1;renderTransactions()};$('#dayFilter').onchange=e=>{filters.day=e.target.value;page=1;renderTransactions()};$('#kindFilter').onchange=e=>{filters.kind=e.target.value;page=1;renderTransactions()};$('#prevPage').onclick=()=>{page=Math.max(1,page-1);renderTransactions()};$('#nextPage').onclick=()=>{page++;renderTransactions()};$('#showTypes').onclick=()=>{$('#kindFilter').value='all';filters.kind='all';$('#kindFilter').focus();$('#kindFilter').scrollIntoView({behavior:'smooth',block:'center'})};
 if(!saved){localStorage.setItem(BASE_STORE,'http://localhost:8080')}connectionRequested=true;connect();}
function cleanBase(v){let s=(v||'').trim().replace(/\/+$/,'');if(!s)return'';if(!/^https?:\/\//i.test(s))s='https://'+s;try{const u=new URL(s);if(!['http:','https:'].includes(u.protocol))return'';return u.origin}catch{return''}}
function setState(mode,label,hint){const n=$('#apiState');n.className='api-state '+(mode==='on'?'connected':mode==='error'?'error':'');n.querySelector('span').textContent=label;$('#liveLabel').textContent=mode==='on'?'실시간 이벤트 수신 중':mode==='error'?'API 연결을 확인하세요':'실시간 수집 준비';$('#feedStatus').textContent=mode==='on'?'수신 중':mode==='error'?'연결 오류':'연결 전';$('#feedStatus').className='feed-status '+(mode==='on'?'on':'');if(hint)$('#connectHint').textContent=hint;$('#connectBtn').textContent=mode==='on'?'연결 해제':mode==='connecting'?'연결 중…':'연결';$('#connectBtn').disabled=mode==='connecting';if(mode==='on')$('#apiNotice').textContent='bach023의 donation 이벤트를 받고 있습니다. 새 이벤트는 이 브라우저에 저장됩니다.';else if(mode==='error')$('#apiNotice').textContent='API 서버에 연결하지 못했습니다. 주소와 서버 실행 상태, HTTPS/WSS 설정을 확인하세요. 누적 데이터는 계속 볼 수 있습니다.';else if(hint)$('#apiNotice').textContent=hint}
function connect(){const base=cleanBase($('#apiBase').value);if(!base){setState('error','주소 확인','유효한 API 주소를 입력하세요');return}localStorage.setItem(BASE_STORE,base);$('#apiBase').value=base;disconnect(false);connectionRequested=true;setState('connecting','연결 중','SOOP Unified Core · bach023 연결 중');let wsUrl=base.replace(/^http:/i,'ws:').replace(/^https:/i,'wss:')+'/v1/ws';try{socket=new WebSocket(wsUrl)}catch{scheduleRetry(base);return}let welcomed=false;socket.onopen=()=>{setState('connecting','연결 중','WebSocket 열림 · Core handshake 대기')};socket.onmessage=e=>{let msg;try{msg=JSON.parse(e.data)}catch{return}if(msg.type==='hello'&&!welcomed){welcomed=true;socket.send(JSON.stringify({action:'subscribe',streamers:['bach023'],events:['donation','MISSION',121]}));if(pingTimer)clearInterval(pingTimer);pingTimer=setInterval(()=>{if(socket?.readyState===1)socket.send(JSON.stringify({action:'ping'}))},20000);setState('connecting','구독 중','bach023 · donation 카테고리 구독 요청')}
 if(msg.type==='subscribed'){if(lastSeq>0)socket.send(JSON.stringify({action:'resume',fromSeq:lastSeq}));setState('on','연결됨','SOOP Unified Core · bach023 · 후원 이벤트 구독')}
 if(msg.type==='event'){lastSeq=Math.max(lastSeq,Number(msg.seq)||0);const ev=msg.event;if(isDonation(ev))addLive(ev,msg.seq)}
 if(msg.type==='gap'){if(Number.isFinite(Number(msg.fromSeq))&&socket?.readyState===1)socket.send(JSON.stringify({action:'resume',fromSeq:lastSeq}));$('#apiNotice').textContent='연결이 혼잡해 일부 이벤트를 다시 확인하고 있습니다.'}
 if(msg.type==='resume_unavailable')$('#apiNotice').textContent='Core 재생 기록 범위를 넘어간 이벤트가 있어 해당 구간은 복구할 수 없습니다. 현재 이벤트 수신은 계속됩니다.';
 if(msg.type==='error')$('#apiNotice').textContent='실시간 API 응답: '+(msg.detail||msg.error||'연결 오류');if(msg.type==='pong'&&watchTimer){clearTimeout(watchTimer);watchTimer=setTimeout(()=>socket?.readyState===1&&socket.send(JSON.stringify({action:'ping'})),45000)}};
 socket.onerror=()=>{};socket.onclose=()=>{if(pingTimer)clearInterval(pingTimer);setState('error','연결 끊김','연결이 끊겼습니다 · 자동 재연결을 시도합니다');if(connectionRequested)scheduleRetry(base)};}
function scheduleRetry(base){if(!connectionRequested)return;if(retryTimer)clearTimeout(retryTimer);retryTimer=setTimeout(()=>{if(connectionRequested){$('#apiBase').value=base;connect()}},5000)}
function disconnect(update=true){if(retryTimer)clearTimeout(retryTimer);retryTimer=null;if(pingTimer)clearInterval(pingTimer);pingTimer=null;if(watchTimer)clearTimeout(watchTimer);watchTimer=null;if(update)connectionRequested=false;if(socket){const s=socket;socket=null;s.onclose=null;try{s.close()}catch{}}if(update)setState('idle','연결 해제','실시간 연결을 해제했습니다 · 누적 데이터는 그대로 표시됩니다')}
function isDonation(e){return !!e&&(e.category==='donation'||(e.donation&&Number(e.donation.amount)>0))&&Number(e.donation?.amount)>0}
function addLive(e,seq){const id=e.providerEventId||e.id||String(seq||'')+':'+String(e.receivedAt||'')+':'+String(e.user?.id||'')+':'+String(e.donation?.amount||'');if(addedIds.has(id))return;addedIds.add(id);const x={day:'실시간',date:new Date(e.receivedAt||Date.now()).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'2-digit',month:'2-digit',day:'2-digit'}).replace(/\. /g,'-').replace(/\./g,''),time:new Date(e.receivedAt||Date.now()).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false}),nickname:e.user?.nickname||'닉네임 미확인',userId:e.user?.id||'unknown',kind:kindLabel(e.donation.kind||e.type),amount:Number(e.donation.amount),message:e.message||'',eventId:id,seq:Number(seq)||0,receivedAt:e.receivedAt||new Date().toISOString()};liveEvents.push(x);if(liveEvents.length>5000){const removed=liveEvents.splice(0,liveEvents.length-5000);removed.forEach(z=>addedIds.delete(z.eventId))}if(seq)lastSeq=Math.max(lastSeq,Number(seq));try{localStorage.setItem(STORE,JSON.stringify(liveEvents));localStorage.setItem(STORE+':seq',String(lastSeq))}catch{liveEvents=liveEvents.slice(-1500);try{localStorage.setItem(STORE,JSON.stringify(liveEvents))}catch{}}renderAll()}
function clearLive(){liveEvents=[];addedIds.clear();lastSeq=0;localStorage.removeItem(STORE);localStorage.removeItem(STORE+':seq');renderAll()}
function renderAll(){renderMetrics();renderChart();renderCategories();renderRanking();renderFeed();populateFilters();renderTransactions()}
function renderMetrics(){const totals=liveEvents.reduce((a,e)=>a+Number(e.amount||0),0);$('#officialTotal').innerHTML=fmt(data.officialTotal)+'<span>개</span>';$('#detailTotal').innerHTML=fmt(data.detailedTotal)+'<span>개</span>';$('#missingTotal').innerHTML=fmt(data.missingTotal)+'<span>개</span>';$('#liveTotal').innerHTML=fmt(totals)+'<span>개</span>';$('#liveCount').textContent=fmt(liveEvents.length)+'건';$('#feedTotal').textContent=fmt(liveEvents.length)}
function renderChart(){const max=Math.max(...Object.values(data.days).map(d=>d.official),1);$('#dayChart').innerHTML=Object.entries(data.days).map(([day,d])=>{const pct=d.official/max*100;const det=d.detail/d.official*100;return `<div class="day-row"><div class="day-label">${day}<small>${d.events||0}건 상세</small></div><div class="bar-stack" title="공식 ${fmt(d.official)}개 / 상세 ${fmt(d.detail)}개"><div class="bar-official" style="width:${pct}%"></div><div class="bar-detail" style="width:${pct*det/100}%"></div></div><div class="day-numbers"><b>${fmt(d.official)}</b>${fmt(d.detail)} 상세</div></div>`}).join('');const gap=Object.values(data.days).reduce((a,d)=>a+(d.official-d.detail),0);$('#chartCaption').textContent=`상세 내역 ${fmt(data.detailedTotal)}개 · 공식 합계와의 차액 ${fmt(gap)}개는 특정 후원자에게 배분하지 않았습니다.`}
function getKindTotals(){return data.transactions.reduce((a,x)=>{const k=x.kind||'기타';a[k]??={amount:0,events:0};a[k].amount+=Number(x.amount)||0;a[k].events++;return a},{})}
function renderCategories(){const all=Object.entries(getKindTotals()).sort((a,b)=>b[1].amount-a[1].amount);const max=all[0]?.[1].amount||1;$('#categoryList').innerHTML=all.map(([k,v])=>`<div class="category-row"><span class="category-name">${kindLabel(k)}</span><div class="category-track"><div class="category-fill" style="width:${Math.max(1,v.amount/max*100)}%"></div></div><span class="category-amount">${fmt(v.amount)}개<small>${v.events}건</small></span></div>`).join('')||'<div class="empty-feed">유형 데이터가 없습니다.</div>'}
function renderRanking(){const grouped=data.transactions.reduce((a,x)=>{const id=x.userId||'unknown';a[id]??={nickname:x.nickname,userId:id,amount:0,events:0};a[id].nickname=x.nickname||a[id].nickname;a[id].amount+=Number(x.amount)||0;a[id].events++;return a},{});const top=Object.values(grouped).sort((a,b)=>b.amount-a.amount||a.userId.localeCompare(b.userId)).slice(0,12);$('#rankBody').innerHTML=top.map((u,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td><span class="rank-name">${esc(u.nickname)}</span></td><td><span class="rank-id">${esc(u.userId)}</span></td><td>${fmt(u.events)}건</td><td class="align-r"><span class="rank-amount">${fmt(u.amount)}</span></td></tr>`).join('');$('#rankTail').textContent=`총 ${Object.keys(grouped).length}명 · 동일 SOOP ID 기준으로 합산`}
function renderFeed(){const items=[...liveEvents].reverse().slice(0,18);if(!items.length){$('#feedList').innerHTML='<div class="empty-feed"><span>⌁</span><b>실시간 연결을 기다리는 중</b><small>API 주소를 확인하면 새 후원 이벤트가 여기에 표시됩니다.</small></div>';return}$('#feedList').innerHTML=items.map(e=>`<div class="feed-item"><span class="feed-time">${esc(e.time)}</span><span><span class="feed-who">${esc(e.nickname)}</span><span class="feed-kind">${esc(kindLabel(e.kind))} · ${esc(e.userId)}</span></span><span class="feed-amount">+${fmt(e.amount)}</span></div>`).join('')}
function populateFilters(){const day=$('#dayFilter'),kind=$('#kindFilter');if(day.options.length===1){Object.keys(data.days).forEach(d=>day.insertAdjacentHTML('beforeend',`<option value="${esc(d)}">${esc(d)}</option>`));day.insertAdjacentHTML('beforeend','<option value="실시간">실시간</option>')}if(kind.options.length===1){[...new Set([...Object.keys(getKindTotals()).map(kindLabel),...liveEvents.map(e=>kindLabel(e.kind))])].sort().forEach(k=>kind.insertAdjacentHTML('beforeend',`<option value="${esc(k)}">${esc(k)}</option>`))}}
function getFiltered(){let all=[...data.transactions.map(x=>({...x,source:'엑셀'})),...liveEvents.map(x=>({...x,source:'실시간'}))];if(filters.day!=='all')all=all.filter(x=>x.day===filters.day);if(filters.kind!=='all')all=all.filter(x=>kindLabel(x.kind)===filters.kind);if(filters.query)all=all.filter(x=>`${x.nickname} ${x.userId}`.toLowerCase().includes(filters.query));return all}
function renderTransactions(){const rows=getFiltered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const list=rows.slice((page-1)*pageSize,page*pageSize);$('#transactionBody').innerHTML=list.map(x=>`<tr><td>${esc(x.day)}</td><td>${esc(x.date)} ${esc(x.time)}</td><td><span class="rank-name">${esc(x.nickname)}</span></td><td>${esc(x.userId)}</td><td><span class="kind-pill ${x.source==='실시간'?'live':''}">${esc(kindLabel(x.kind))}</span></td><td class="align-r"><span class="amount-cell">${fmt(x.amount)}</span></td><td class="msg-cell" title="${esc(x.message||'')}">${esc(x.message||'—')}</td></tr>`).join('')||'<tr><td colspan="7" style="text-align:center;padding:28px;color:#879187">조건에 맞는 거래가 없습니다.</td></tr>';$('#rowCount').textContent=`${fmt(rows.length)}건`;$('#pageLabel').textContent=`${page} / ${pages}`;$('#prevPage').disabled=page<=1;$('#nextPage').disabled=page>=pages}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
