let state={boxes:[],pending:[],streamerId:'',overlay:{x:4,y:72,scale:1.45}},connection={state:'idle'};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2100)}
async function api(path,opts){const r=await fetch('/v1/roulette'+path,{headers:{'content-type':'application/json'},...opts}),j=await r.json();if(!r.ok)throw Error(j.error||'처리하지 못했습니다.');return j}
function render(){
 const list=state.boxes.filter(b=>b.status!=='archived');
 $('boxes').innerHTML=list.length?list.map(b=>{const p=Math.min(100,b.collected/b.goal*100),active=b.id===state.activeBoxId;return `<article class="box ${b.status==='completed'?'done':''}"><div class="box-top"><div><h3>${esc(b.title)}</h3><small>${b.status==='completed'?'🎉 추첨 완료':active?'● 코드 없이 자동 참여':'대기 중 · #코드로 참여'}</small></div><span class="tag">${active?'대표 상자':'#'+esc(b.code)}</span></div><div class="track"><div class="fill" style="width:${p}%"></div></div><div class="row"><b>${b.collected.toLocaleString()}개</b><span>${b.goal.toLocaleString()}개 · ${p.toFixed(1)}%</span></div><div class="shares">${b.winner?`<div class="row"><b>🏆 ${esc(b.winner.nickname)}</b><b>당첨</b></div>`:b.shares.slice().sort((a,c)=>c.amount-a.amount).slice(0,5).map(s=>`<div class="row"><span>${esc(s.nickname)}</span><b>${s.amount.toLocaleString()}개 · ${(s.amount/b.goal*100).toFixed(1)}%</b></div>`).join('')}</div>${b.status==='collecting'&&!active?`<button class="soft" onclick="setActive('${b.id}')">대표 상자로 선택</button>`:''}<button class="danger" onclick="archiveBox('${b.id}')">${b.status==='completed'?'목록에서 정리':'상자 종료'}</button></article>`}).join(''):'<div class="empty"><div style="font-size:40px">📦</div><b>아직 열린 상자가 없습니다</b><br>오른쪽에서 첫 상자를 열어보세요.</div>';
 $('pending').innerHTML=state.pending.length?state.pending.map(p=>`<div class="row"><span>${esc(p.nickname)}</span><b>${p.amount.toLocaleString()}개</b></div>`).join(''):'<div class="hint" style="padding:12px 0">보관 중인 별풍선이 없습니다.</div>';
 $('streamer').value=state.streamerId||'';renderConnection();syncOverlayControls();
}
function renderConnection(){const ready=connection.ready;$('connection').textContent=connection.label||(state.streamerId?'연결 확인 중':'SOOP 연결 준비');$('streamLabel').textContent=connection.nickname?`${connection.nickname} (${state.streamerId})`:state.streamerId||'아이디를 입력하세요';document.querySelector('.dot').style.background=ready?'#52d49c':connection.online?'#ffc85c':'#8e829a'}
async function createBox(){try{await api('/boxes',{method:'POST',body:JSON.stringify({title:$('titleInput').value,code:$('code').value,goal:Number($('goal').value)})});$('titleInput').value=$('code').value=$('goal').value='';toast('새 상자를 열었습니다.')}catch(e){toast(e.message)}}
async function setActive(boxId){await api('/active-box',{method:'POST',body:JSON.stringify({boxId})});toast('코드 없는 후원이 이 상자로 들어갑니다.')}
async function archiveBox(id){if(confirm('상자를 종료할까요? 모인 지분은 보관함으로 돌아갑니다.'))await api('/boxes/'+id,{method:'DELETE'})}
async function connectStream(){try{connection={label:'방송국 확인 중…'};renderConnection();await api('/settings',{method:'POST',body:JSON.stringify({streamerId:$('streamer').value})});await checkConnection();toast('방송국을 확인했습니다.')}catch(e){connection={label:'연결하지 못했습니다.'};renderConnection();toast(e.message)}}
async function checkConnection(){if(!state.streamerId)return;try{connection=(await api('/connection')).connection;renderConnection()}catch{connection={label:'연결 상태를 다시 확인하는 중…'};renderConnection()}}
async function testDonation(){try{await api('/test-donation',{method:'POST',body:JSON.stringify({nickname:$('testNick').value,amount:Number($('testAmount').value),message:$('testMessage').value})});toast('가상 후원을 보냈습니다.')}catch(e){toast(e.message)}}
function copyOverlay(){navigator.clipboard.writeText($('overlayUrl').value);toast('방송 화면 주소를 복사했습니다.')}
function syncOverlayControls(){if(!$('overlayScale'))return;$('overlayScale').value=state.overlay.scale;$('overlayX').value=state.overlay.x;$('overlayY').value=state.overlay.y;$('scaleValue').textContent=Math.round(state.overlay.scale*100)+'%'}
let saveTimer;function overlayChanged(){clearTimeout(saveTimer);$('scaleValue').textContent=Math.round(Number($('overlayScale').value)*100)+'%';saveTimer=setTimeout(()=>api('/overlay-settings',{method:'POST',body:JSON.stringify({scale:Number($('overlayScale').value),x:Number($('overlayX').value),y:Number($('overlayY').value)})}),120)}
function preset(x,y,scale){$('overlayX').value=x;$('overlayY').value=y;$('overlayScale').value=scale;overlayChanged()}
const previewPanel=[...document.querySelectorAll('.panel')].find(p=>p.querySelector('h2')?.textContent==='연출 테스트');previewPanel.insertAdjacentHTML('beforebegin','<section class="panel"><h2>방송 화면 배치</h2><div class="hint">OBS 소스 하나에서 모든 상자 크기와 위치를 조절합니다.</div><div class="form"><label>전체 크기 <b id="scaleValue">145%</b></label><input id="overlayScale" type="range" min="0.6" max="2.5" step="0.05" oninput="overlayChanged()"><label>가로 위치</label><input id="overlayX" type="range" min="0" max="80" step="1" oninput="overlayChanged()"><label>세로 위치</label><input id="overlayY" type="range" min="0" max="85" step="1" oninput="overlayChanged()"><div class="row"><button class="soft" onclick="preset(4,72,1.45)">왼쪽 아래</button><button class="soft" onclick="preset(38,65,1.6)">가운데</button><button class="soft" onclick="preset(70,72,1.45)">오른쪽 아래</button></div></div></section>');
$('overlayUrl').value=location.origin+'/roulette/overlay';new EventSource('/v1/roulette/events').onmessage=e=>{state=JSON.parse(e.data).state;render()};api('/state').then(x=>{state=x.state;render();checkConnection()});setInterval(checkConnection,3500);
